services:
 
  # ollama and API
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: missing
    tty: true
    restart: unless-stopped
    # Expose Ollama API outside the container stack
    ports:
      - 11434:11434
      - 8053:53
    volumes:
      - ollama:/volume1/docker/portainer/Files/AppData/ollama
    # GPU support (turn off by commenting with # if you don't have an nvidia gpu)
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities:
#                - gpu
 
  # webui, nagivate to http://localhost:8069/ to use
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: missing
    volumes:
      - open-webui:/volume1/docker/portainer/Files/AppData/ollama/webui
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://localhost:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
 
volumes:
  ollama: {}
  open-webui: {}

